version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env.docker-compose
    volumes:
      - sqlite:/app/db
    networks:
      - appNetwork
networks:
  appNetwork:
    driver: bridge
volumes:
  sqlite:
